service: uploader-service

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${self:custom.currentStage}
  logRetentionInDays: 30
  timeout: 30
  environment:
    fileUploaderS3BucketName: ${file(./config/serverless.config.${self:custom.currentStage}.yml):fileUploaderS3BucketName}
    fileTranscodedS3BucketName: ${file(./config/serverless.config.${self:custom.currentStage}.yml):fileTranscodedS3BucketName}
    S3Endpoint: ${file(./config/serverless.config.${self:custom.currentStage}.yml):S3Endpoint}
    environmentTag: ${file(./config/serverless.config.${self:custom.currentStage}.yml):environmentTag}
  apiGateway:
    restApiId: ${file(./config/serverless.config.${self:custom.currentStage}.yml):restApiId}
    restApiRootResourceId: ${file(./config/serverless.config.${self:custom.currentStage}.yml):restApiRootResourceId}

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  fileUploaderS3BucketName: ${file(./config/serverless.config.${self:custom.currentStage}.yml):fileUploaderS3BucketName}
  fileTranscodedS3BucketName: ${file(./config/serverless.config.${self:custom.currentStage}.yml):fileTranscodedS3BucketName}
  apigwBinary:
    types:
      - 'multipart/form-data'
    apiGatewayName: apigateway-${self:custom.currentStage}
  s3:
    port: 8401
    directory: ./tmp-s3
  serverless-offline:
    port: 5002

functions:
  UPLOADER_SERVICE:
    name: 'UPLOADER_SERVICE_${opt:stage, self:custom.defaultStage}'
    description: Uploader Service
    handler: src/index.handler
    events:
      - http:
          path: /upload
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - Content-Length
              - X-Requested-With          
          authorizer:
            type: COGNITO_USER_POOLS
            arn: ${file(./config/serverless.config.${self:custom.currentStage}.yml):authorizer}
              
resources:
  Resources:
    FileUploaderS3Bucket:
      DependsOn:
        - TranscodeVideoPermissionFileUploaderS3Bucket
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileUploaderS3BucketName}
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: "s3:ObjectCreated:*"
              Function: ${file(./config/serverless.config.${self:custom.currentStage}.yml):transcoderLambdaFuntionArn}

    FileTranscodedS3Bucket:
      DependsOn:
        - PushVideoDynamoDB    
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileTranscodedS3BucketName}
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: "s3:ObjectCreated:*"
              Function: ${file(./config/serverless.config.${self:custom.currentStage}.yml):pushVideoToDBLambdaFuntionArn}

    TranscodeVideoPermissionFileUploaderS3Bucket:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: ${file(./config/serverless.config.${self:custom.currentStage}.yml):transcoderLambdaFuntionArn}
        Action: "lambda:InvokeFunction"
        Principal: "s3.amazonaws.com"
        SourceArn: "arn:aws:s3:::${self:custom.fileUploaderS3BucketName}"

    PushVideoDynamoDB:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: ${file(./config/serverless.config.${self:custom.currentStage}.yml):pushVideoToDBLambdaFuntionArn}
        Action: "lambda:InvokeFunction"
        Principal: "s3.amazonaws.com"
        SourceArn: "arn:aws:s3:::${self:custom.fileTranscodedS3BucketName}"

    FileUploaderS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: FileUploaderS3Bucket
        PolicyDocument:
          Statement:
            - Sid: LambdaCrudObject
              Effect: Allow
              Principal: 
                AWS: ${file(./config/serverless.config.${self:custom.currentStage}.yml):lambdaIamRole}
              Action:
                - s3:GetObject
                - s3:DeleteObject
                - s3:PutObject
              Resource:
                Fn::Join: [ "", ["arn:aws:s3:::", { "Ref": "FileUploaderS3Bucket" }, "/*"] ]
plugins:
 - serverless-apigw-binary        
 - serverless-offline
 - serverless-s3-local